[package]
name = "enums"
version = "0.1.0"
edition = "2024"

[lib]
name = "enums"
path = "lib.rs"
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = {version = "2.0.104", features = ["full"]}
